[build]
target = "x86_64-os.json"

#This tells cargo that it should recompile the core and compiler_builtins libraries.
#The latter is required because it is a dependency of core
# can only be built with nightly version
[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
panic-abort-tests = true

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
